"""
Local metadata about cached repodata files
"""

from ._base import ExtrasForbiddenModel
from .types import SHA256Str


class RepodataInfo(ExtrasForbiddenModel):
    """
    Repodata's `*.info.json` files
    """

    blake2_256_nominal: SHA256Str = ...
    blake2_256: SHA256Str = ...
    cache_control: str = ...
    etag: str = ...
    mod: str = ...
    mtime_ns: int = ...
    refresh_ns: int = ...
    size: int = ...
    url: str = ...
