name: Test

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: intelligence-ai/jsonschema@v0.2.0
      - run: jsonschema lint *.schema.json --verbose
      - run: jsonschema fmt *.schema.json --check --verbose
